Assorted fixes for Python 3.10 support
microsoft/debugpy pull request #690
Opened 2021-08-05 18:39 UTC by int19h

Split test/requirements.txt into two different lists, one for py2, and the other for py3; update package versions in py3 list as needed to support py3.10.

Fix usage of deprecated threading functions getName(), setName(), isDaemon(), and currentThread().

Refactor test_invalid_breakpoints to be more declarative to handle Python version differences more easily and clearly, and fix it for py3.10.

Disable Django tests on py3.10 (#689).

Disable gevent tests on py3.10 (#688).

2021-08-05 18:40 UTC, int19h commented
@fabioz I wasn't sure what the best place for the new threading helpers was, so this is a best guess - lmk if you'd prefer to organize that code differently.

2021-08-05 18:59 UTC, fabioz requested changes
Just some minors, mainly pointing that I think we should actually use the new method formats without worries about backward compatibility since I just checked and even Python 2.6 already had those.

(i.e.: just use t.name / t.daemon / threading.current_thread directly).

2021-08-05 18:59 UTC, fabioz commented on src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_utils.py
> +def current_thread():
`threading.current_thread` is already available in Python 2.6, so, I don't think we actually need this helper function. If an alias is interesting, I think it should be in `pydevd_constants`, right after the `threading` module is imported.

2021-08-05 18:59 UTC, fabioz commented on src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_utils.py
> +def get_thread_name(t):
`threading.Thread.name` is already available in Python 2.6, so, I don't think we actually need to do the try..except.

Maybe we can just inline this method and just use `t.name` where needed...

2021-08-05 18:59 UTC, fabioz commented on src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py
> +        if hasattr(self, 'name'):
Is this really needed? Ideally I think we could just set `thread.name = name` where needed.

2021-08-05 18:59 UTC, fabioz commented on src/debugpy/_vendored/pydevd/pydevd.py
> +                    is_daemon = t.daemon
`t.daemon` is available in `Python 2.6` already, so, I don't think we need the try..except.

2021-08-05 19:14 UTC, int19h commented
I wasn't sure if that's also the case for Jython etc? If it's okay to just use the new APIs everywhere, that's even better.

2021-08-05 19:18 UTC, fabioz commented
> I wasn't sure if that's also the case for Jython etc? If it's okay to just use the new APIs everywhere, that's even better.

It should be (only Jython 2.7 is supported, so, it should be compatible with Python 2.7 in that regard).

2021-08-06 10:11 UTC, fabioz approved these changes

2021-08-06 10:12 UTC, merged